version: 2.1

references:
  workspace_root: &workspace_root
    ~/repo
  defaults: &defaults
    working_directory: *workspace_root

orbs:
  slack: circleci/slack@3.4.1
  npm: sugarshin/npm@0.1.5
  gh-pages: sugarshin/gh-pages@0.0.6

executors:
  nodejs_browsers:
    <<: *defaults
    docker:
      - image: sugarshin/circleci-node-browsers-fonts:12.13.1
  buildpack_deps:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:latest

jobs:
  build:
    executor: nodejs_browsers
    steps:
      - checkout
      - npm/install:
          production: true
      - run: /bin/bash scripts/build.sh
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
      - store_artifacts:
          path: pdf
          destination: pdf
  slack_notify:
    executor: slack/alpine
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: "slides.sugarshin.net has been updated! <https://slides.sugarshin.net>"
          webhook: ${SLACK_WEBHOOK_URL}

workflows:
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - gh-pages/deploy:
          name: deploy
          executor: buildpack_deps
          attach-workspace: true
          workspace-root: *workspace_root
          git-user: CircleCI
          git-email: s+circleci@sugarshin.net
          ssh-fingerprints: a7:49:7e:a0:5e:9d:5a:e5:a9:da:5d:5e:a3:58:87:8f
          requires:
            - build
          filters:
            branches:
              only: master
      - slack_notify:
          requires:
            - deploy
