version: 2.1

orbs:
  nodejs: circleci/node@5.0.3
  gh-pages: sugarshin/gh-pages@1.0.1
  jq: circleci/jq@2.2.0
  shellcheck: circleci/shellcheck@3.1.1

executors:
  nodejs_browsers:
    working_directory: &workspace_root ~/project
    docker:
      - image: sugarshin/circleci-node-browsers-fonts:13.0.0-node12.17.0
  base:
    working_directory: *workspace_root
    docker:
      - image: cimg/base:current-22.04

jobs:
  build:
    executor: nodejs_browsers
    steps:
      - checkout
      - jq/install
      - nodejs/install-packages
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
      - store_artifacts:
          path: pdf
          destination: pdf

workflows:
  main:
    jobs:
      - shellcheck/check:
          image-tag: current-22.04
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - shellcheck/check
      - gh-pages/deploy:
          name: deploy
          executor: base
          attach-workspace: true
          workspace-root: *workspace_root
          git-user: CircleCI
          git-email: s+circleci@sugarshin.net
          ssh-fingerprints: a7:49:7e:a0:5e:9d:5a:e5:a9:da:5d:5e:a3:58:87:8f
          requires:
            - build
          filters:
            branches:
              only: master
