version: 2.1

orbs:
  nodejs: circleci/node@5.0.3
  gh-pages: sugarshin/gh-pages@1.0.1
  shellcheck: circleci/shellcheck@3.1.1
  browser-tools: circleci/browser-tools@1.4.1

executors:
  nodejs_browsers:
    working_directory: &workspace_root ~/project
    docker:
      - image: cimg/node:20.8.1-browsers
  base:
    working_directory: *workspace_root
    docker:
      - image: cimg/base:current-22.04

jobs:
  build:
    executor: nodejs_browsers
    steps:
      - run:
          name: Install dependencies and update locale
          command: |
            sudo apt update
            sudo apt -y install \
              language-pack-ja \
              fonts-noto \
              fonts-noto-color-emoji \
              fonts-liberation \
              fonts-dejavu
            sudo locale-gen ja_JP.UTF-8
            sudo update-locale LANG=ja_JP.UTF-8
      - browser-tools/install-chrome
      - checkout
      - nodejs/install-packages
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
      - store_artifacts:
          path: pdf
          destination: pdf

workflows:
  main:
    jobs:
      - shellcheck/check:
          image-tag: current-22.04
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - shellcheck/check
      - gh-pages/deploy:
          pre-steps:
            - run: |
                mkdir -p ~/.ssh      
                ssh-keyscan github.com >> ~/.ssh/known_hosts
          name: deploy
          executor: base
          attach-workspace: true
          workspace-root: *workspace_root
          git-user: CircleCI
          git-email: s+circleci@sugarshin.net
          ssh-fingerprints: 79:93:e1:03:46:18:7b:6d:17:e3:79:04:64:99:b6:95
          requires:
            - build
          filters:
            branches:
              only: main
