version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  npm: sugarshin/npm@0.1.7
  nodejs: circleci/node@4.7.0
  gh-pages: sugarshin/gh-pages@0.0.6
  jq: circleci/jq@2.2.0

executors:
  nodejs_browsers:
    working_directory: &workspace_root ~/repo
    docker:
      - image: sugarshin/circleci-node-browsers-fonts:13.0.0-node12.17.0
  base:
    working_directory: *workspace_root
    docker:
      - image: cimg/base:stable-20.04

jobs:
  build:
    executor: nodejs_browsers
    steps:
      - checkout
      - nodejs/install-packages:
          override-ci-command: npm ci --production
      - jq/install
      - run:
          command: npm run build
          environment:
            NODE_ENV: production
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - dist
      - store_artifacts:
          path: dist
          destination: dist
      - store_artifacts:
          path: pdf
          destination: pdf
  slack_notify:
    executor: slack/alpine
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: "slides.sugarshin.net has been updated! <https://slides.sugarshin.net>"
          webhook: ${SLACK_WEBHOOK_URL}

workflows:
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - gh-pages/deploy:
          name: deploy
          executor: base
          attach-workspace: true
          workspace-root: *workspace_root
          git-user: CircleCI
          git-email: s+circleci@sugarshin.net
          ssh-fingerprints: a7:49:7e:a0:5e:9d:5a:e5:a9:da:5d:5e:a3:58:87:8f
          requires:
            - build
          filters:
            branches:
              only: master
      - slack_notify:
          requires:
            - deploy
